community-tags:
  - CI
  - continuous integration
  - docker
  - docker-db
  - script languages
  - UDFs
community-project-name: Script Languages Container Tool
community-project-description: |
  The Script-Languages-Container-Tool (exaslct) is the build tool for the script language container.
  You can build, export and upload script-language container from so-called flavors which are description how to build the script language container.
  [Script-Languages-Container-Tool](https://github.com/exasol/script-languages-container-tool).