FROM {{base_test_build_run}}

RUN mkdir /exaudf
RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY /flavor_test_build_run_packages.yaml /build_info/flavor_test_build_run_packages.yaml
RUN true # workaround for https://github.com/moby/moby/issues/37965
