name: Checks

on:
  pull_request:

jobs:

  lint-job:
    name: Linting and Type checks (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.14.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Unit Tests
        run: poetry run nox -s unit-tests

      - name: Run Lint
        run: poetry run nox -s lint

      - name: Run type-check
        run: poetry run nox -s type-check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ".lint-python-${{ matrix.python-version }}.txt"
          path: .lint.txt
