name: Check if versions are consistent

on:
  push:
    tags-ignore:
      - '**'
  pull_request:

jobs:
  check-version-numbers:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: '3.10'
          poetry-version: '1.8.2'
      - name: Check Release
        run: poetry run python3 scripts/build/check_release.py
