name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
      - "master"

jobs:

  CI:
    uses: ./.github/workflows/merge-gate.yml
    secrets: inherit
    permissions:
      contents: read

  Metrics:
    needs: [ CI ]
    uses: ./.github/workflows/report.yml
    permissions:
      contents: read
