name: GPU Tests

on:
  workflow_call:

jobs:

  prep-testbed-gpu:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.6.0

      - id: set-matrix
        run: |
          ALL_TESTS=`poetry run -- nox -s integration-test-list -- --test-set gpu-only`
          echo "matrix=$ALL_TESTS" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-gpu:
    needs: prep-testbed-gpu
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
        test-path: ${{fromJson(needs.prep-testbed-gpu.outputs.matrix)}}
    runs-on:
      labels: int-linux-x64-4core-gpu-t4-ubuntu24.04-1
    name: GPU Test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.6.0
        with:
          python-version: '${{ matrix.python_version }}'
          use-cache: 'false'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run ${{ matrix.test-path.name }}
        run: poetry run -- python "${{ matrix.test-path.path }}"
