name: Integration Tests

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
          required: true
      DOCKER_PASSWORD:
          required: true
jobs:

  prep-testbed:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.6.0

      - id: set-matrix
        run: |
          ALL_TESTS=`poetry run -- nox -s integration-test-list -- --test-set default`
          echo "matrix=$ALL_TESTS" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-all:
    needs: prep-testbed
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
        test-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
    runs-on: ubuntu-24.04
    name: ${{ matrix.test-path.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.6.0
        with:
          python-version: '${{ matrix.python_version }}'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run test ${{ matrix.test-path.name }}
        run: poetry run -- python ${{ matrix.test-path.path }}
        env: # Set the secret as an input
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}
