name: Check bash scripts

on: [push, pullrequest]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: ./scripts/build/shellcheck.sh
