name: Slow-Checks

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
          required: true
      DOCKER_PASSWORD:
          required: true
jobs:

  slow-tests-approval:
    name: Approve Slow Tests
    runs-on: ubuntu-24.04

    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval

    # Replace the steps below with the required actions
    # and/or add additional jobs if required
    # Note:
    #   If you add additional jobs, make sure they are added as a requirement
    #   to the approve-merge job's input requirements (needs).
    steps:
      - name: Tests
        run: echo "Slow tests approved"


  integration-tests:
    needs: slow-tests-approval
    name: Integrations
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  gpu-tests:
    needs: slow-tests-approval
    name: Integrations
    uses: ./.github/workflows/gpu-tests.yml
    secrets: inherit
