name: Slow-Checks

on:
  workflow_call:
    secrets:
      CI4_DOCKERHUB_USERNAME:
          required: true
      CI4_DOCKERHUB_TOKEN:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
        required: true
jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["minimum_python_version"]'
    permissions:
      contents: read

  build-extended-python-matrix:
    name: Build Extended Python Version Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["extended_python_versions"]'
    permissions:
      contents: read

  integration-tests:
    name: Integrations
    needs:
      - build-extended-python-matrix
    uses: ./.github/workflows/integration-tests.yml
    secrets:
      CI4_DOCKERHUB_TOKEN: ${{ secrets.CI4_DOCKERHUB_TOKEN }}
      CI4_DOCKERHUB_USERNAME: ${{ secrets.CI4_DOCKERHUB_USERNAME }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-extended-python-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.extended_python_versions }}

  gpu-tests:
    name: Integrations
    needs:
      - build-extended-python-matrix
    uses: ./.github/workflows/gpu-tests.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-extended-python-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.extended_python_versions }}
