name: Slow-Checks

on:
  workflow_call:
    secrets:
      CI4_DOCKERHUB_USERNAME:
          required: true
      CI4_DOCKERHUB_TOKEN:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
        required: true
jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["minimum_python_version", "python_versions"]'
    permissions:
      contents: read

  extended-python-versions:
    name: Determine Extended Python Versions
    needs:
      - build-matrix
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - id: set-matrix
        env:
          BASE_MATRIX: ${{ needs.build-matrix.outputs.matrix }}
        run: |
          MIN_VERSION=`jq -r '.minimum_python_version[0]' <<< "$BASE_MATRIX"`
          MAX_VERSION=`jq -r '.python_versions[]' <<< "$BASE_MATRIX" | sort -V | tail -1`
          VERSIONS=`jq -cn --arg min "$MIN_VERSION" --arg max "$MAX_VERSION" '[$min, $max] | unique'`
          echo "matrix={\"python_version\":$VERSIONS}" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  integration-tests:
    name: Integrations
    needs:
      - extended-python-versions
    uses: ./.github/workflows/integration-tests.yml
    secrets:
      CI4_DOCKERHUB_TOKEN: ${{ secrets.CI4_DOCKERHUB_TOKEN }}
      CI4_DOCKERHUB_USERNAME: ${{ secrets.CI4_DOCKERHUB_USERNAME }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.extended-python-versions.outputs.matrix) }}
    with:
      python_version: ${{ matrix.python_version }}

  gpu-tests:
    name: Integrations
    needs:
      - extended-python-versions
    uses: ./.github/workflows/gpu-tests.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.extended-python-versions.outputs.matrix) }}
    with:
      python_version: ${{ matrix.python_version }}

  saas-tests:
    name: Integrations
    needs:
      - build-matrix
    uses: ./.github/workflows/integration-saas-tests.yml
    secrets:
      INTEGRATION_TEAM_SAAS_STAGING_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
      INTEGRATION_TEAM_SAAS_STAGING_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}

